name: genomic-fm
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - aom=3.9.1
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - cpython=3.10.19
  - dav1d=1.2.1
  - dbus=1.16.2
  - ffmpeg=8.0.1
  - filelock=3.20.3
  - fmt=12.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - fsspec=2026.1.0
  - gdk-pixbuf=2.44.4
  - giflib=5.2.2
  - glslang=16.2.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=12.3.0
  - icu=78.2
  - jinja2=3.1.6
  - kaldi=5.5.1172
  - lame=3.100
  - lcms2=2.18
  - lerc=4.0.0
  - libabseil=20250512.1
  - libass=0.17.4
  - libavif16=1.3.0
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcxx=21.1.8
  - libde265=1.0.15
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.3
  - libheif=1.19.7
  - libhwloc=2.12.2
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - liblzma=5.8.2
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopenvino=2025.4.1
  - libopenvino-arm-cpu-plugin=2025.4.1
  - libopenvino-auto-batch-plugin=2025.4.1
  - libopenvino-auto-plugin=2025.4.1
  - libopenvino-hetero-plugin=2025.4.1
  - libopenvino-ir-frontend=2025.4.1
  - libopenvino-onnx-frontend=2025.4.1
  - libopenvino-paddle-frontend=2025.4.1
  - libopenvino-pytorch-frontend=2025.4.1
  - libopenvino-tensorflow-frontend=2025.4.1
  - libopenvino-tensorflow-lite-frontend=2025.4.1
  - libopus=1.6.1
  - libpng=1.6.54
  - libprotobuf=6.31.1
  - librsvg=2.60.0
  - libsqlite=3.51.2
  - libtiff=4.7.1
  - libtorch=2.9.1
  - libusb=1.0.29
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libvpx=1.15.2
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - markupsafe=3.0.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - nomkl=1.0
  - openfst=1.8.4
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.6.0
  - optree=0.18.0
  - pango=1.56.4
  - pcre2=10.47
  - pillow=12.1.0
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pugixml=1.15
  - pybind11=3.0.1
  - pybind11-abi=11
  - pybind11-global=3.0.1
  - python=3.10.19
  - python_abi=3.10
  - pytorch=2.9.1
  - rav1e=0.7.1
  - readline=8.3
  - scipy=1.15.2
  - sdl2=2.32.56
  - sdl3=3.2.30
  - setuptools=80.9.0
  - shaderc=2025.5
  - sleef=3.9.0
  - snappy=1.2.2
  - spirv-tools=2025.4
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2022.3.0
  - tk=8.6.13
  - torchaudio=2.9.1
  - torchcodec=0.8.1
  - torchvision=0.25.0
  - torchvision-extra-decoders=0.0.2
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - accelerate==1.12.0
      - anyio==4.12.1
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.1.0
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - biopython==1.86
      - bleach==6.3.0
      - captum==0.8.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - coloredlogs==15.0.1
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - cyvcf2==0.31.4
      - debugpy==1.8.19
      - decorator==5.2.1
      - defusedxml==0.7.1
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fonttools==4.61.1
      - fqdn==1.5.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - ipykernel==7.1.0
      - ipython==8.38.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - kiwisolver==1.4.9
      - lark==1.3.1
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mistune==3.2.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.5.1
      - prometheus-client==0.24.1
      - prompt-toolkit==3.0.52
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.23
      - pyfaidx==0.9.0.3
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pysam==0.23.3
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - seaborn==0.13.2
      - send2trash==2.1.0
      - six==1.17.0
      - soupsieve==2.8.3
      - stack-data==0.6.3
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tokenizers==0.22.2
      - tomli==2.4.0
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.6
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==2.6.3
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0

